= He Yingxu - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a retailer analysis application used for retailers to keep track of their customers and transactions. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *Completed product class together with order's GUI*
** What it does: allows the user to add and delete product. Preceding undo commands can be reversed by using the redo command.
** Justification: It enables the customers to add new products into the storage. This feature is also a premise for other new features of our application.
** Highlights: This enhancement requires new commands and parsers to handle the execution related to the new product class, as well as new elements in the UI component to visualize the product list.

* *Minor enhancement*: added Money class to enable working with money.
** what is does: Money class can recognize all the invalid currency type in the ISO 4217 code. Support operations like addition and subtraction. 
** Justification: This feature makes sure product & order class functions properly as well as supports the features of our recommendation engine. 

* *Minor enhancement*: added basic GUI for order class.
* *Code contributed*: https://github.com/CS2103JAN2018-T15-B1/main/blob/master/collated/functional/YingxuH.md[Functional Code], https://github.com/CS2103JAN2018-T15-B1/main/blob/master/collated/test/YingxuH.md[Test Code]
* *Other contributions*:
*** General 
** help teammates implements command and model implementations for order class. (Commit https://github.com/CS2103JAN2018-T15-B1/main/pull/34/commits/7afb006202449bcf21cc45bb3a7e2cf168cec555[7afb006], https://github.com/CS2103JAN2018-T15-B1/main/pull/34/commits/5b84edd89f6cb13a8224d4a29b1eefe7830561d7[5b84edd]) (Pull request https://github.com/CS2103JAN2018-T15-B1/main/pull/40[#40])
*** 

*** Project management:
** maintain the issue tracker during our project progress 1.1 to 1.5. 
** help solve issues reported during the in-class testing session. https://github.com/CS2103JAN2018-T15-B1/main/issues/52[52]

*** Enhancements to existing features:
** added product and order in GUI
** resized the customers' list in GUI (Pull requests https://github.com/CS2103JAN2018-T15-B1/main/pull/30[#30], https://github.com/CS2103JAN2018-T15-B1/main/pull/34[#34])
*** Documentation:
** Did cosmetic tweaks to existing contents of the User Guide.
** draw UI and Model UML diagram in DeveloperGuide to help developers better visualize the architect (posted by my teammate).
*** Community:
** PRs reviewed 

